// Auto-generated. Do not edit!

// (in-package rococo_navigation.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class FollowCorridorGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.target_X = null;
      this.target_Y = null;
      this.max_vel = null;
    }
    else {
      if (initObj.hasOwnProperty('target_X')) {
        this.target_X = initObj.target_X
      }
      else {
        this.target_X = 0.0;
      }
      if (initObj.hasOwnProperty('target_Y')) {
        this.target_Y = initObj.target_Y
      }
      else {
        this.target_Y = 0.0;
      }
      if (initObj.hasOwnProperty('max_vel')) {
        this.max_vel = initObj.max_vel
      }
      else {
        this.max_vel = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FollowCorridorGoal
    // Serialize message field [target_X]
    bufferOffset = _serializer.float32(obj.target_X, buffer, bufferOffset);
    // Serialize message field [target_Y]
    bufferOffset = _serializer.float32(obj.target_Y, buffer, bufferOffset);
    // Serialize message field [max_vel]
    bufferOffset = _serializer.float32(obj.max_vel, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FollowCorridorGoal
    let len;
    let data = new FollowCorridorGoal(null);
    // Deserialize message field [target_X]
    data.target_X = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [target_Y]
    data.target_Y = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [max_vel]
    data.max_vel = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'rococo_navigation/FollowCorridorGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '6213a78c6faf5ade64348156f926f0c1';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Goal
    # target position 
    float32 target_X
    float32 target_Y
    # max velocity [m/s]
    float32 max_vel
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FollowCorridorGoal(null);
    if (msg.target_X !== undefined) {
      resolved.target_X = msg.target_X;
    }
    else {
      resolved.target_X = 0.0
    }

    if (msg.target_Y !== undefined) {
      resolved.target_Y = msg.target_Y;
    }
    else {
      resolved.target_Y = 0.0
    }

    if (msg.max_vel !== undefined) {
      resolved.max_vel = msg.max_vel;
    }
    else {
      resolved.max_vel = 0.0
    }

    return resolved;
    }
};

module.exports = FollowCorridorGoal;
