
shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 5.0

footprint_padding: 0.01 #Anexo
clearing_rotation_allowed: true #Anexo
clearing_radius: 0.2 #Anexo

oscillation_timeout: 10.0
oscillation_distance: 0.2

# local planner - default is trajectory rollout
base_local_planner: "dwa_local_planner/DWAPlannerROS"

base_global_planner: "global_planner/GlobalPlanner"

#"navfn/NavfnROS" 
#alternatives: global_planner/GlobalPlanner, carrot_planner/CarrotPlanner

#NavfnROS:
#  allow_unknown: true

GlobalPlanner:

  old_navfn_behavior: false
  use_quadratic: true
  use_dijkstra: true
  use_grid_path: false

  allow_unknown: true

  planner_window_x: 0.0
  planner_window_y: 0.0
  default_tolerance: 0.0
  
  publish_scale: 100
  planner_costmap_publish_frequency: 0.0
  
  lethal_cost: 253
  neutral_cost: 66 #50
  cost_factor: 0.55 #3.0
  publish_potential: false

