; Auto-generated. Do not edit!


(cl:in-package rococo_navigation-msg)


;//! \htmlinclude FollowPersonGoal.msg.html

(cl:defclass <FollowPersonGoal> (roslisp-msg-protocol:ros-message)
  ((person_id
    :reader person_id
    :initarg :person_id
    :type cl:integer
    :initform 0)
   (max_vel
    :reader max_vel
    :initarg :max_vel
    :type cl:float
    :initform 0.0))
)

(cl:defclass FollowPersonGoal (<FollowPersonGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowPersonGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowPersonGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name rococo_navigation-msg:<FollowPersonGoal> is deprecated: use rococo_navigation-msg:FollowPersonGoal instead.")))

(cl:ensure-generic-function 'person_id-val :lambda-list '(m))
(cl:defmethod person_id-val ((m <FollowPersonGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rococo_navigation-msg:person_id-val is deprecated.  Use rococo_navigation-msg:person_id instead.")
  (person_id m))

(cl:ensure-generic-function 'max_vel-val :lambda-list '(m))
(cl:defmethod max_vel-val ((m <FollowPersonGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader rococo_navigation-msg:max_vel-val is deprecated.  Use rococo_navigation-msg:max_vel instead.")
  (max_vel m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowPersonGoal>) ostream)
  "Serializes a message object of type '<FollowPersonGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'person_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'person_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'person_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'person_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'person_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'person_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'person_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'person_id)) ostream)
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'max_vel))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowPersonGoal>) istream)
  "Deserializes a message object of type '<FollowPersonGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'person_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'person_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'person_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'person_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'person_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'person_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'person_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'person_id)) (cl:read-byte istream))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'max_vel) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowPersonGoal>)))
  "Returns string type for a message object of type '<FollowPersonGoal>"
  "rococo_navigation/FollowPersonGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowPersonGoal)))
  "Returns string type for a message object of type 'FollowPersonGoal"
  "rococo_navigation/FollowPersonGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowPersonGoal>)))
  "Returns md5sum for a message object of type '<FollowPersonGoal>"
  "bc669fb86b77765b83a3fdd1f702ad5e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowPersonGoal)))
  "Returns md5sum for a message object of type 'FollowPersonGoal"
  "bc669fb86b77765b83a3fdd1f702ad5e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowPersonGoal>)))
  "Returns full string definition for message of type '<FollowPersonGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%# target person~%uint64  person_id~%# max velocity [m/s]~%float32 max_vel~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowPersonGoal)))
  "Returns full string definition for message of type 'FollowPersonGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Goal~%# target person~%uint64  person_id~%# max velocity [m/s]~%float32 max_vel~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowPersonGoal>))
  (cl:+ 0
     8
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowPersonGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowPersonGoal
    (cl:cons ':person_id (person_id msg))
    (cl:cons ':max_vel (max_vel msg))
))
